sudo: required

services:
  - docker

before_install:
  - docker build -t zeshan316/docker-react -f Dockerfile.dev .

scripts: 
  - docker run -e CI=true zeshan316/docker-react npm run test -- --coverage